version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:latest
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  api:
    image: doodlestudentapi
    restart: always
    depends_on:
      - db
      - etherpad
      - mail
    ports:
      - "8080:8080"
    environment:
      - quarkus.datasource.jdbc.url=jdbc:mysql://db:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
      - doodle.internalPadUrl=http://etherpad:9001/
    command:
      - java
      - -Doodle.internalPadUrl=http://etherpad:9001/
      - -Dquarkus.datasource.jdbc.url=jdbc:mysql://db:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
      - -jar
      - target/tlcdemoApp-1.0.0-SNAPSHOT-runner.jar

  front:
    image: doodlestudentfront
    depends_on:
      - api
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ../front/nginx1.conf:/etc/nginx/conf.d/default.conf:ro
